version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./api/.docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
    command: >
      bash -c "go build -o /app/main &&
               /app/main"

  front:
    build:
      context: .
      dockerfile: ./front/.docker/Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    tty: true

