openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Returns a greeting message.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hello'
  /goodbye:
    get:
      summary: Returns a goodbye message.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/goodbye'
components:
  schemas:
    hello:
      type: object
      properties:
        message:
          type: string
    goodbye:
      type: object
      properties:
        message:
          type: string
